### ISSUE TITLE
ffish in browser: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0)

### ISSUE THREAD

**Issue by sinh-png** [fairy-stockfish/Fairy-Stockfish#623]
I countered this issue when trying to initialize ffish-es6 0.7.4 in browser:

```
Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (ffish.js:9:9235)
    at ffish.js:9:10918
```

My codes:
```typescript
import Module from 'ffish-es6';

let ffish = null;
new (Module as any)().then((loadedModule:any) => {
    ffish = loadedModule;
    console.log(`initialized ${ffish} ${loadedModule}`);
});
```

Thank you for checking this out!

**Comment by sinh-png** [comment]
Solved it by copying ffish.wasm to where I serve the page!
