### ISSUE TITLE
Why can't Fairy-Stockfish use NNUE in to Crazyhouse and Atomic

### ISSUE THREAD

**Issue by M-DinhHoangViet** [fairy-stockfish/Fairy-Stockfish#684]
This is when the BOT plays Crazyhouse with NNUE
`Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\PV\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\PV\Downloads\LichessBOT-Viet-main (1)\LichessBOT-Viet-main\game.py", line 44, in run
    self._make_move()
  File "C:\Users\PV\Downloads\LichessBOT-Viet-main (1)\LichessBOT-Viet-main\game.py", line 99, in _make_move
    uci_move, offer_draw, resign = self.lichess_game.make_move()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PV\Downloads\LichessBOT-Viet-main (1)\LichessBOT-Viet-main\lichess_game.py", line 81, in make_move
    move, info = self._make_engine_move()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PV\Downloads\LichessBOT-Viet-main (1)\LichessBOT-Viet-main\lichess_game.py", line 599, in _make_engine_move
    result = self.engine.play(self.board, limit, info=chess.engine.INFO_ALL, ponder=ponder)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PV\AppData\Roaming\Python\Python311\site-packages\chess\engine.py", line 2795, in play
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\PV\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PV\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\PV\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\PV\AppData\Roaming\Python\Python311\site-packages\chess\engine.py", line 1685, in play
    return await self.communicate(UciPlayCommand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PV\AppData\Roaming\Python\Python311\site-packages\chess\engine.py", line 1094, in communicate
    return await command.result
           ^^^^^^^^^^^^^^^^^^^^
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)`

![image](https://github.com/fairy-stockfish/Fairy-Stockfish/assets/134517889/b0f6df4d-c326-41da-b4a6-69e1ad3acd60)

**Comment by M-DinhHoangViet** [comment]
Only Crazyhouse and Atomic get this error when running Lichess Bot

**Comment by ianfab** [comment]
The crazyhouse net seems to be missing the nnue suffix in your screenshot

**Comment by M-DinhHoangViet** [comment]
Okay thanks for the quick response. Maybe it's because of too much that I missed
